# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

jobs:
  - job: sonarAnalysis
    steps:
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'SonarCloud'
        organization: 'mhadzimehanovic'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'mhadzimehanovic_sonartest'
        cliProjectName: 'sonartest'
        cliSources: '.'
    - task: SonarCloudAnalyze@1